# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveinfo',
            name='groups',
            field=models.CharField(default='default_group', max_length=16),
            preserve_default=False,
        ),
    ]
