# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0002_liveinfo_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveinfo',
            old_name='groups',
            new_name='group',
        ),
    ]
