# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_team', '0003_auto_20170713_0425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveInfo',
        ),
    ]
