# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='TeamCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
